### ISSUE TITLE
bytes type does not work

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cdc-sink#20]
It seems to get escaped an extra time

**Comment by bobvawter** [comment]
The incoming byte value is being passed into cleanValue as a hex-escaped string like “\x112358”, which is then not decoded, but inserted as-is into the sink database.  An incorrect change that makes the existing, commented-out test pass would be to update `cleanValue()` with code such as the following:

```
case string:
		if strings.HasPrefix(t, `\x`) {
			return hex.DecodeString(t[2:])
		}
		// bit, date, inet, interval, string, time, timestamp, timestamptz, uuid,
		// collated strings
		return value, nil
```

This is, of course, wrong since any incoming "real" string value that begins with `\x` would be escaped.  Either cdc-sink or the resulting SQL statements needs to effect the necessary `STRING::BYTES` conversion.  This would tend to imply that cdc-sink needs knowledge of which columns are of `BYTES` type, or the SQL statement used to insert the data needs to apply some kind of type coercion.

**Comment by BramGruneir** [comment]
Bytes now work.
